### ISSUE TITLE
logic flow diagram

### ISSUE THREAD

**Issue by blakemiles** [21hackathon/git-money#12]
git-money logic flow diagram for MVP functionality

**Comment by blakemiles** [comment]
Have on paper. Will put on giffly tonight.

**Comment by masonicGIT** [comment]
Hey Miles, 

Thanks for taking this up. Will you be able to place it in the trello board :-). I made a list specifically for this

https://trello.com/b/r0vsgd2o/21-hackathon

**Comment by blakemiles** [comment]
http://www.gliffy.com/go/publish/9814339 (interactive)

http://www.gliffy.com/go/publish/image/9814339/L.png (image)
