### ISSUE TITLE
logo psd + png 

### ISSUE THREAD

**Issue by chuck-nasty** [21hackathon/git-money#17]
working on it right now.. will deliver it tonight..

**Comment by chuck-nasty** [comment]
[logo.zip](https://github.com/21hackathon/git-money/files/95527/logo.zip)

**Comment by chuck-nasty** [comment]
wait a minmin -- i'll just put em here

**Comment by chuck-nasty** [comment]
![git_money_icon](https://cloud.githubusercontent.com/assets/8636448/12413068/d71a696e-be40-11e5-887d-bfa796c9ffce.png)
![git_money_logo](https://cloud.githubusercontent.com/assets/8636448/12413069/d71ba428-be40-11e5-9279-e06152eafcfe.png)

**Comment by chuck-nasty** [comment]
PNG ^^

**Comment by chuck-nasty** [comment]
I put the psd in the zip if anyone wants to change this. Please have at it, my ms paint chops are only so good :)

**Comment by blakemiles** [comment]
I really like those!

What would the first one look like with a slightly smaller G and the shadow from the second one added?

**Comment by chuck-nasty** [comment]
ya youre right, its kinda off size wise ill play w it in the AM. the one on the twtr i think it nicer like slim and better matched up. (https://twitter.com/gitmoneyco)
